spring:
  application:
    name: DevConnect

  datasource:
    url: jdbc:mysql://localhost:3306/devconnect
    username: root
    password: harsh@2005
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: gharshgupta490@gmail.com
    password: miow mwcg dxxu qixh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

cloudinary:
  cloud-name: dnrrxjurs
  api-key: 426587575266173
  api-secret: HzzK27S0J_jsHrKoQqak6VWhPQE